### ISSUE TITLE
Tela Mapa Apresenta Uncaught RuntimeErrors

### ISSUE THREAD

**Issue by Koda-ms** [SteffanoP/cata-sucata#16]
Oi, @vicentegalencar  ! Eu estava testando o projeto por aqui e toda vez que clico para visualizar a tela de Mapa, o seguinte erro aparece:

![Captura de tela 2023-08-24 222141](https://github.com/SteffanoP/cata-sucata/assets/66442236/2f66310c-80db-487a-badd-62db061ed2ac)

Eu fiz uma pesquisa prévia sobre, e o que encontrei é algo referente ao link da API do Google Maps está sendo duplicado e isso pode causar problemas, assim como diz esse erro no Console do Google Chrome.

![Captura de tela 2023-08-24 222552](https://github.com/SteffanoP/cata-sucata/assets/66442236/7d870131-a4cb-4cd4-bc0d-db2684b312fe)

Pensei que tínhamos solucionado enquanto analisava a PR, porém esse aviso persiste. Você poderia verificar, por favor?

**Comment by SteffanoP** [comment]
Corrigido em #18
